### ISSUE TITLE
Nice to have common Typealiases

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/NimbleExtension#20]
After discussing with you guys on Slack https://nimble-co.slack.com/archives/G418DBL2W/p1599637496007200.

The first thing that's nice to have in this project is `Typealias`. I looked inside current `The1`, `Omise` and `7-Chat`, I intend to add some below:

- EmptyRequestResult.swift contains:

```swift
public enum EmptyRequestResult {
    case success
    case failure(Error)
}
```

- Typealias.swift contains:
```swift
public typealias Headers = [String: String]
public typealias Parameters = [String: Any]

public typealias Callback<T> = (T) -> Void
public typealias CompletionHandler = () -> Void
public typealias ResultCompletion<T> = (Result<T>) -> Void
public typealias EmptyResultCompletion = (EmptyRequestResult) -> Void
```

And remove current 2 files: `Callback.swift` and `CompletionHandler.swift`

**Comment by NutanNiraula** [comment]
@vnntsu I have mixed opinion about this one, keeping typealiases in a module would mean that we will need to import that module in order to use it. So for every file we need to use `Callback` for example that file will add `import NimbleExtension` I say let's add this through project template rather than in module, that way it is added in app level scope. What do you think?

**Comment by vnntsu** [comment]
@NutanNiraula you're right, we will unhappy with importing it everywhere we need.

I'm will move it to the template instead
